# Generated by Django 4.2.7 on 2025-05-23 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('recycling_info', models.TextField()),
                ('environmental_impact', models.TextField()),
                ('sustainability_tips', models.TextField()),
                ('decomposition_time', models.CharField(blank=True, max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Object Categories',
            },
        ),
        migrations.CreateModel(
            name='ScannedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scanned_objects/')),
                ('detected_object', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('eco_points_earned', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_data.objectcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('is_eco_friendly', models.BooleanField(default=False)),
                ('sustainability_score', models.IntegerField(default=0, help_text='Score from 0-100')),
                ('recycling_instructions', models.TextField(blank=True)),
                ('eco_alternatives', models.TextField(blank=True)),
                ('environmental_impact', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_data.objectcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_data.productbarcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
